export const EntityNameConst = Object.freeze({
  PERMISSION: 'permission',
  ROLE: 'role',
  ROLE_PERMISSION: 'role_permission',
  UPLOAD: 'upload',
  UPLOAD_CLEAN_HISTORY: 'upload_clean_history',
  USER: 'user',
  USER_LOG: 'user_log',
  TOKEN: 'token',
  VOCABULARY: 'vocabulary',
  TOPIC: 'topic',
  VOCABULARY_VIEW: 'vocabulary_view',
  CLASSROOM: 'classroom',
  EXAM: 'exam',
  QUESTION: 'question',
  EXAM_ATTEMPT: 'exam_attempt',
  ANSWER: 'answer',
  STUDENT_ANSWER: 'student_answer',
  CLASS_STUDENT: 'class_student',
});
